language: node_js
node_js:
    - 8
script:
    - echo "Deploy!!"

install:
    - npm install -g firebase-tools
    - npm install --prefix functions

after_success:
    - firebase deploy --project appsimake --token $FIREBASE_TOKEN
